# .github/workflows/cd.yml

name: CD - Deploy via Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download image URI
        uses: actions/download-artifact@v3
        with:
          name: strapi-image-uri

      - name: Read image URI
        id: image
        run: |
          IMAGE_URI=$(cat image-uri.txt)
          echo "image_uri=$IMAGE_URI" >> $GITHUB_ENV
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="strapi_image=${{ env.image_uri }}"
