name: CI - Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image URI
        id: image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: docker push $IMAGE_URI

      - name: Save image URI for CD
        run: echo "${{ steps.image.outputs.image_uri }}" > image-uri.txt

      - name: Upload image URI as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: strapi-image-uri
          path: image-uri.txt
