name: Deploy Strapi to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: 724772070195.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: naina-strapi-repo
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        run: |
          # Push commit SHA tag
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Push latest tag
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Terraform Init, Plan, and Apply
        env:
          TF_VAR_strapi_image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        run: |
          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve

      # ✅ New Step: Get latest Task Definition ARN
      - name: Get latest Task Definition ARN
        id: get-task-def
        run: |
          latest_task_def=$(aws ecs list-task-definitions --family-prefix strapi-task --sort DESC --max-items 1 --region us-east-1 --query 'taskDefinitionArns[0]' --output text)
          echo "Latest task def is: $latest_task_def"
          echo "task_def_arn=$latest_task_def" >> $GITHUB_ENV

      # ✅ New Step: Generate dynamic codedeploy.json
      - name: Generate codedeploy.json dynamically
        run: |
          cat <<EOF > codedeploy.json
          {
            "version": 1,
            "Resources": [
              {
                "TargetService": {
                  "Type": "AWS::ECS::Service",
                  "Properties": {
                    "TaskDefinition": "${{ env.task_def_arn }}",
                    "LoadBalancerInfo": {
                      "ContainerName": "strapi",
                      "ContainerPort": 1337
                    }
                  }
                }
              }
            ]
          }
          EOF

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name strapi-codedeploy-app \
            --deployment-group-name strapi-deployment-group \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --region us-east-1 \
            --revision '{"revisionType":"AppSpecContent","appSpecContent":{"content": "'"$(cat codedeploy.json)"'"}}' \
            --description "GitHub Actions triggered deployment"
